// import React from 'react'

// const Dall3 = ({ onNext, onChange }) => {
//     return (
//         <div>
//             <div>step 3</div>
//             <button onClick={onNext}>Next</button>
//             <input type="text" name="firstName" onChange={onChange} />
//             <input type="text" name='lastName' onChange={onChange} />
//         </div>
//     )
// }

// export default Dall3

import { useState } from 'react'
// import styles from '@/app/(Pages)/sell/dall/Dall3.module.css'
import styles from '@/app/(Pages)/sell/ThirdStep/dall/Dall3.module.css'
import FieldInfo from '@/app/Components/(liteComponents)/FieldInfo/FieldInfo'
import GradientButton from '@/app/Components/GradientButton/GradientButton'
import TextArea from '@/app/Components/(liteComponents)/TextAreaComponent/TextArea'
import DropDownList from '@/app/Components/(liteComponents)/DropDownList/DropDownList'

const categoryArr = [
    {
        name: "DALL-E 2",
        value: "DALL-E 2"
    },
    {
        name: "DALL-E 3",
        value: "DALL-E 3"
    },
];

const Dall3 = ({ onNext }) => {
    const [selectCategory, setselectCategory] = useState(categoryArr[0]);
    return (
        <div className={styles.parentContainer}>
            <h2 className={styles.heading}>Prompt File</h2>

            {/* version */}
            <FieldInfo title="Version" description="Select the version of DALL-E you're using." />

            {/* dropdown */}
            <DropDownList
                options={categoryArr}
                value={selectCategory}
                onChange={setselectCategory}
            />

            {/* prompt */}
            <FieldInfo title="*Prompt" description="Put any variables in [square brackets]." />
            <TextArea placeholder="An Impressionist oil painting of [Flower] in a purple vase.." rows="18" />


            {/* *Testing Prompt */}
            <FieldInfo title="*Testing Prompt" description="One example of your prompt with all variables filled in, e.g. [animal] -> koala. We'll use this to test <br/> your prompt - buyers will not see this. Do not include any instructions here." />
            <TextArea placeholder="An Impressionist oil painting of rose in a purple vase.." rows="18" />

            {/* *Prompt Instructions */}
            <FieldInfo title="*Prompt Instructions" description="Any extra tips or examples for the buyer on how to use this prompt." />
            <TextArea placeholder="To get the most out of this prompt you need to.." rows="18" />

            {/* *Example images */}
            <FieldInfo title="*Example images" description="Upload 9 example images generated by this prompt (no collages or edits)" />
            <div className={styles.uploadImage}>+</div>

            {/* next button */}
            <div className={styles.nextBtn}>
                <GradientButton title="Next" onClick={onNext} />
            </div>

        </div>
    )
}

export default Dall3