import { Finlandica } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header/Header";
import Footer from "./Components/Footer/Footer";

const finlandica = Finlandica({ subsets: ["latin"] });

export const metadata = {
  title: "Dollar Prompt | Buy & Sell Prompts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={finlandica.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
