import styles from '@/app/Components/(liteComponents)/InputImage/InputImage.module.css'
import { FaPlus } from "react-icons/fa6";
import { useState } from 'react';
import FieldInfo from '../FieldInfo/FieldInfo';

const InputImage = ({ onChange }) => {
    const [selectedFiles, setselectedFiles] = useState([])
    const [singleFile, setsingleFile] = useState([])
    function onChanges(e) {
        onChange(e);
        if (e.target.files.length > 1) {
            // Add all selected files to singleFile state
            setsingleFile(prev => [...prev, ...Array.from(e.target.files)]);

            // Update selectedFiles with all selected files
            setselectedFiles(prev => [...prev, ...Array.from(e.target.files)]);
        } else {
            // Add the single selected file to singleFile state
            setsingleFile(prev => [...prev, e.target.files[0]]);

            // Update selectedFiles with the single selected file
            setselectedFiles(prev => [...prev, e.target.files[0]]);
        }
    }

    if (selectedFiles.length > 7) {
        setselectedFiles(selectedFiles.slice(0, 7))
    }
    // console.log(URL.createObjectURL(selectedFiles[0]))

    const deleteFunc = (index) => {
        const updatedFiles = selectedFiles.filter((_, scan) => scan !== index); // Filter 
        setselectedFiles(updatedFiles);
    }

    return (
        <div className={styles.outputImgContainer}>
            <FieldInfo title="*Example images" description="Upload 7 example images generated by this prompt (no collages or edits)" />
            {
                selectedFiles.map((e, index) =>
                    <div key={index} className={styles.singleImgContainer}>
                        <FaPlus className={styles.cancel} onClick={() => deleteFunc(index)} />
                        {/* <img src="/assets/imageAssets/img1.webp" alt="" /> */}
                        <img
                            src={URL.createObjectURL(e)}
                            alt="" />
                    </div>
                )
            }
            <input disabled={selectedFiles.length > 6 ? true : false} onChange={onChanges} className={styles.imageInput} type="file" name="myfiles" accept="image/jpeg,image/png,video/*" multiple required />
        </div>
    )
}

export default InputImage;